spring:
  profiles:
    active: dev
  application:
    name: neo4j-spring-boot

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password

  data:
    neo4j:
      database: neo4j

scoring:
  skill-weight: 10
  role-weight: 5
  company-weight: 5